BestRestaurants/Models/Cuisine.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BestRestaurants.Models
{
  public class Cuisine
  {
    
    [Range(1, int.MaxValue, ErrorMessage = "You must add your restaurant to a cuisine. Have you created a cuisine yet?")]
    public int CuisineId { get; set; }
    
    [Required(ErrorMessage = "The food can't be empty!")]
    public string Name { get; set; }
    public string Type { get; set; }
    public List<Restaurant> Restaurants { get; set; }
  }
}

BestRestaurants/Controllers/CuisinesController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using BestRestaurants.Models;
using System.Collections.Generic;
using System.Linq;

namespace BestRestaurants.Controllers
{
  public class CuisinesController : Controller
  {
    private readonly BestRestaurantsContext _db;

    public CuisinesController(BestRestaurantsContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Cuisine> model = _db.Cuisines.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Cuisine cuisine)
    {
      _db.Cuisines.Add(cuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Cuisine thisCuisine = _db.Cuisines
                                .Include(cuisine => cuisine.Restaurants)
                                .FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    public ActionResult Edit(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    [HttpPost]
    public ActionResult Edit(Cuisine cuisine)
    {
      _db.Cuisines.Update(cuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      _db.Cuisines.Remove(thisCuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

BestRestaurants/Controllers/RestaurantsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using BestRestaurants.Models;
using System.Collections.Generic;
using System.Linq;

namespace BestRestaurants.Controllers
{
  public class RestaurantsController : Controller
  {
    private readonly BestRestaurantsContext _db;

    public RestaurantsController(BestRestaurantsContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Restaurant> model = _db.Restaurants.Include(restaurants => restaurants.Cuisine).ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Restaurant restaurant)
    {
      if (!ModelState.IsValid)
      {
        ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Name");
        return View(restaurant);
      }
      else
      {
        _db.Restaurants.Add(restaurant);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }

    public ActionResult Details(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants
                                      .Include(restaurant => restaurant.Cuisine)
                                      .Include(restaurant => restaurant.JoinEntities)
                                      .ThenInclude(join => join.Food)      
                                      .FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      return View(thisRestaurant);
    }

    public ActionResult Edit(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Name");
      return View(thisRestaurant);
    }

    [HttpPost]
    public ActionResult Edit(Restaurant restaurant)
    {
      _db.Restaurants.Update(restaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      return View(thisRestaurant);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      _db.Restaurants.Remove(thisRestaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddFood(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantId == id);
      ViewBag.FoodId = new SelectList(_db.Foods, "FoodId", "FoodType");
      return View(thisRestaurant);
    }

    [HttpPost]
    public ActionResult AddFood(Restaurant restaurant, int FoodId)
    {
      #nullable enable
      RestaurantFood? joinEntity = _db.RestaurantFoods.FirstOrDefault(join => (join.FoodId == FoodId && join.RestaurantId == restaurant.RestaurantId));
      #nullable disable
      
      if (joinEntity == null && FoodId != 0)
      {
        _db.RestaurantFoods.Add(new RestaurantFood() { FoodId = FoodId, RestaurantId = restaurant.RestaurantId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = restaurant.RestaurantId });
    }  

    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      RestaurantFood joinEntry = _db.RestaurantFoods.FirstOrDefault(entry => entry.RestaurantFoodId == joinId);
      _db.RestaurantFoods.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }


  }
}

BestRestaurants/Views/Cuisine/Create.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Cuisine

<h4>Add a new Cuisine</h4>
@using (Html.BeginForm())
{ 
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <input type="submit" value="Add a new cuisine" />
}

<p>@Html.ActionLink("Show all cuisines", "Index")</p>

BestRestaurants/Views/Cuisine/Delete.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Cuisine

<h2>Are you certain you want to delete this cuisine?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}

@Html.ActionLink("Back to cuisine list", "Index")

BestRestaurants/Views/Cuisine/Details.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Category
@using BestRestaurants.Models

<h2>Cuisine Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)<h3>

@if (@Model.Restaurants.Count == 0)
{
  <h3>No restaurants have been added for this cuisine yet!</h3>
} 
else
{
  <h3>Restaurants:</h3>
  <ul>
    @foreach (Restaurant restaurant in Model.Restaurants)
    {
      <li>@Html.ActionLink($"{restaurant.Description}", "Details", "Restaurants", new { id = restaurant.RestaurantId })</li>
    }
  </ul>
}

<p>@Html.ActionLink("Edit Cuisine", "Edit", new { id = Model.CuisineId })</p>
<p>@Html.ActionLink("Delete Cuisine", "Delete", new { id = Model.CuisineId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>

BestRestaurants/Views/Cuisine/Edit.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Category

<h2>Edit</h2>

<h4>Edit this cuisine: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.CuisineId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to list", "Index")</p>