BestRestaurants/Models/Food.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BestRestaurants.Models
{
  public class Food
  {
    public int FoodId { get; set; }

    [Required(ErrorMessage = "The food can't be empty!")]
    public string FoodType { get; set; }
    public string FoodPrice { get; set; }

    public List<RestaurantFood> JoinEntities { get;}
  }
}

BestRestaurants/Controllers/FoodsController.cs
using Microsoft.AspNetCore.Mvc;
using BestRestaurants.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BestRestaurants.Controllers
{
  public class FoodsController : Controller
  {
    private readonly BestRestaurantsContext _db;

    public FoodsController(BestRestaurantsContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Foods.ToList());
    }

    public ActionResult Details(int id)
    {
      Food thisFood = _db.Foods
                          .Include(food => food.JoinEntities)
                          .ThenInclude(join => join.Restaurant)
                          .FirstOrDefault(food => food.FoodId == id);
      return View(thisFood);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Food food)
    {
      _db.Foods.Add(food);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddRestaurant(int id)
    {
      Food thisFood = _db.Foods.FirstOrDefault(foods => foods.FoodId == id);
      ViewBag.RestaurantId = new SelectList(_db.Restaurants, "RestaurantId", "Name");
      return View(thisFood);
    }

    [HttpPost]
    public ActionResult AddRestaurant(Food food, int RestaurantId)
    {
      #nullable enable
      RestaurantFood? joinEntity = _db.RestaurantFoods.FirstOrDefault(join => (join.RestaurantId == RestaurantId && join.FoodId == food.FoodId));
      #nullable disable
      if (joinEntity == null && RestaurantId != 0)
      {
        _db.RestaurantFoods.Add(new RestaurantFood() { RestaurantId = RestaurantId, FoodId = food.FoodId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = food.FoodId });
    }

    public ActionResult Edit(int id)
    {
      Food thisFood = _db.Foods.FirstOrDefault(foods => foods.FoodId == id);
      return View(thisFood);
    }

    [HttpPost]
    public ActionResult Edit(Food food)
    {
      _db.Foods.Update(food);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Food thisFood = _db.Foods.FirstOrDefault(foods => foods.FoodId == id);
      return View(thisFood);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Food thisFood = _db.Foods.FirstOrDefault(foods => foods.FoodId == id);
      _db.Foods.Remove(thisFood);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      RestaurantFood joinEntry = _db.RestaurantFoods.FirstOrDefault(entry => entry.RestaurantFoodId == joinId);
      _db.RestaurantFoods.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

BestRestaurants/Views/Foods/AddRestaurant.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Food

<h2>Add a Restaurant</h2>

<h4>Add a Restaurant to this Food: @Html.DisplayFor(model => model.FoodType)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.FoodId)

    @Html.Label("Select restaurant")
    @Html.DropDownList("RestaurantId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

BestRestaurants/Views/Foods/Create.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Food

<h4>Add a new Food</h4>
<p>@Html.ValidationMessageFor(model => model.FoodType, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.FoodType)
  @Html.TextBoxFor(model => model.FoodType)

  @Html.LabelFor(model => model.FoodPrice)
  @Html.TextBoxFor(model => model.FoodPrice)

  <input type="submit" value="Add new food" class="btn btn-success" />
}
<p>@Html.ActionLink("Show all foods", "Index")</p>

BestRestaurants/Views/Foods/Delete.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Food

<h2>Are you sure you want to delete this type of food?</h2>

@Html.DisplayNameFor(model => model.FoodType): @Html.DisplayFor(model => model.FoodType)

@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

@Html.ActionLink("Back to List", "Index")

BestRestaurants/Views/Foods/Details.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurants.Models
@model BestRestaurants.Models.Food

<h2>Food Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.FoodType): @Html.DisplayFor(model => model.FoodType)</h3>
<h3>@Html.DisplayNameFor(model => model.FoodPrice): @Html.DisplayFor(model => model.FoodPrice)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This food does not belong to any restaurants</p>
}
else
{
  <h4>Restaurants the food belongs to:</h4>
  <ul>
  @foreach(RestaurantFood join in Model.JoinEntities)
  {
    <li>@join.Restaurant.Name</li>
    @using (Html.BeginForm("DeleteJoin", "Foods"))
    {
      @Html.Hidden("joinId", @join.RestaurantFoodId)
      <input type="submit" value="Delete"/>
    }
  }
  </ul>
}

<p>@Html.ActionLink("Edit Food", "Edit", new { id = Model.FoodId })</p>
<p>@Html.ActionLink("Add a Restaurant", "AddRestaurant", new { id = Model.FoodId })</p>
<p>@Html.ActionLink("Delete Food", "Delete", new { id = Model.FoodId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>

BestRestaurants/Views/Foods/Edit.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Food

<h2>Edit</h2>

<h4>Edit this food: @Html.DisplayFor(model => model.FoodType)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.FoodId)

  @Html.LabelFor(model => model.FoodType)
  @Html.EditorFor(model => model.FoodType)

  @Html.LabelFor(model => model.FoodPrice)
  @Html.TextBoxFor(model => model.FoodPrice)

  <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to list", "Index")</p>

BestRestaurants/Views/Foods/Index.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurants.Models;

<h1>Foods</h1>

@if (Model.Count == 0)
{
  <h3>No foods have been added yet!</h3>
}

@foreach (Food food in Model)
{
    <li>@Html.ActionLink($"{food.FoodType}", "Details", new { id = food.FoodId })</li>
}

<p>@Html.ActionLink("Add new Food", "Create")</p>

<p>@Html.ActionLink("Home", "Index", "Home")</p>